### PR TITLE
Lbfgs

### PR DESCRIPTION
**Pull request by L-Xiafeng**
oneflow,strong_wolfe训练结果
```
num_epoch: 100, loss: 0.09013008

real    1m17.526s
user    2m24.450s
sys     0m50.515s
```
torch,strong_wolfe训练结果
```
num_epoch: 100, loss: 0.09780428

real    1m10.364s
user    1m9.138s
sys     0m5.576s
```

### CODE REVIEW

**Comment by L-Xiafeng** [comment]
> 由于精度问题，目前必须要运行在float64下

在pytorch下float32使用Tensor core同样出现了bug
```
closure,pde_loss: 0.8725715279579163, bc_loss: 3.639425039291382, loss: 4.511996746063232
closure,pde_loss: 4.067536354064941, bc_loss: 3.3354265689849854, loss: 7.402962684631348
closure,pde_loss: 1.5117862224578857, bc_loss: 3.579805374145508, loss: 5.091591835021973
closure,pde_loss: 25.865110397338867, bc_loss: 6.740477561950684, loss: 32.605587005615234
closure,pde_loss: 11.224387168884277, bc_loss: 4.6799635887146, loss: 15.904350280761719
closure,pde_loss: 3.6631672382354736, bc_loss: 5.676549911499023, loss: 9.339716911315918
closure,pde_loss: 40.851097106933594, bc_loss: 96.81107330322266, loss: 137.66217041015625
closure,pde_loss: 29.3653507232666, bc_loss: 9.922810554504395, loss: 39.28816223144531
closure,pde_loss: 1.1186163425445557, bc_loss: 11.421914100646973, loss: 12.54053020477295
closure,pde_loss: 3.073915481567383, bc_loss: 11.66961669921875, loss: 14.743532180786133
closure,pde_loss: 0.3885897696018219, bc_loss: 6.216750144958496, loss: 6.605340003967285
closure,pde_loss: 1.4874460697174072, bc_loss: 6.410816669464111, loss: 7.898262977600098
closure,pde_loss: 0.49880141019821167, bc_loss: 6.051626682281494, loss: 6.5504279136657715
closure,pde_loss: 1.4973660707473755, bc_loss: 6.434812545776367, loss: 7.932178497314453
closure,pde_loss: 0.6238651275634766, bc_loss: 6.092759132385254, loss: 6.7166242599487305
closure,pde_loss: 4.335739612579346, bc_loss: 7.748441696166992, loss: 12.08418083190918
closure,pde_loss: 2.121267557144165, bc_loss: 6.247790813446045, loss: 8.369058609008789
closure,pde_loss: 0.9410799741744995, bc_loss: 8.891839027404785, loss: 9.832919120788574
closure,pde_loss: 4.96576452255249, bc_loss: 11.9487886428833, loss: 16.914552688598633
closure,pde_loss: 2.178380012512207, bc_loss: 6.851734161376953, loss: 9.03011417388916
closure,pde_loss: 71.79255676269531, bc_loss: 13.346463203430176, loss: 85.13902282714844
closure,pde_loss: 2634.9208984375, bc_loss: 152.30673217773438, loss: 2787.2275390625
closure,pde_loss: 725062400.0, bc_loss: 2058.980224609375, loss: 725064448.0
closure,pde_loss: 0.0, bc_loss: 24767275008.0, loss: 24767275008.0
closure,pde_loss: nan, bc_loss: nan, loss: nan
closure,pde_loss: nan, bc_loss: nan, loss: nan
```

**Comment by L-Xiafeng** [comment]
strong_wolfe算法在pytorch下float32使用Tensor core同样出现了bug，loss卡在2.05
```
num_epoch: 1, loss: 14.47976
num_epoch: 2, loss: 4.572992
num_epoch: 3, loss: 2.53499
num_epoch: 4, loss: 2.146353
num_epoch: 5, loss: 2.055364
num_epoch: 6, loss: 2.054437
num_epoch: 7, loss: 2.054437
num_epoch: 8, loss: 2.054437
num_epoch: 9, loss: 2.054437
num_epoch: 10, loss: 2.054437
num_epoch: 11, loss: 2.054437
```

**Comment by L-Xiafeng** [comment]
oneflow使用float32，storng_wolfe会出现除0错误
```
num_epoch: 1, loss: 20.27788
num_epoch: 2, loss: 9.325695
num_epoch: 3, loss: 6.476326
num_epoch: 4, loss: 6.2593
num_epoch: 5, loss: 6.205925
num_epoch: 6, loss: 6.20342
num_epoch: 7, loss: 6.203114
num_epoch: 8, loss: 6.203025
num_epoch: 9, loss: 6.20162
num_epoch: 10, loss: 6.201736
num_epoch: 11, loss: 6.201506
num_epoch: 12, loss: 6.187042
num_epoch: 13, loss: 6.187009
num_epoch: 14, loss: 6.187009
num_epoch: 15, loss: 6.187007
num_epoch: 16, loss: 6.187007
num_epoch: 17, loss: 6.186919
num_epoch: 18, loss: 6.186851
num_epoch: 19, loss: 6.186278
num_epoch: 20, loss: 6.186099
num_epoch: 21, loss: 6.186099
num_epoch: 22, loss: 6.162659
num_epoch: 23, loss: 6.162573
num_epoch: 24, loss: 6.16252
num_epoch: 25, loss: 6.162031
num_epoch: 26, loss: 6.16202
num_epoch: 27, loss: 6.162041
Traceback (most recent call last):
  File "OneScience/benchmark/laplace/laplace2d.py", line 85, in <module>
    loss = opt.step(closure=closure)
  File "oneflow/python/oneflow/optim/optimizer.py", line 116, in decorated_step
    return step(*args, **kwargs)
  File "oneflow/python/oneflow/nn/optimizer/lbfgs.py", line 328, in step
    loss, flat_grad, t, ls_func_evals = _strong_wolfe(
  File "oneflow/python/oneflow/nn/optimizer/lbfgs.py", line 78, in _strong_wolfe
    t = _cubic_interpolate(
  File "oneflow/python/oneflow/nn/optimizer/lbfgs.py", line 29, in _cubic_interpolate
    d1 = g1 + g2 - 3 * ((f1 - f2) / (x1 - x2))
ZeroDivisionError: float division by zero
```

**Comment by L-Xiafeng** [comment]
100epoch训练结果
oneflow：
```
num_epoch: 1, loss: 14.48055
num_epoch: 2, loss: 6.732059
num_epoch: 3, loss: 6.299437
num_epoch: 4, loss: 6.100668
num_epoch: 5, loss: 5.50751
num_epoch: 6, loss: 3.554403
num_epoch: 7, loss: 2.936174
num_epoch: 8, loss: 2.567143
num_epoch: 9, loss: 2.39656
num_epoch: 10, loss: 2.120131
num_epoch: 11, loss: 2.034712
num_epoch: 12, loss: 1.960153
num_epoch: 13, loss: 1.944783
num_epoch: 14, loss: 1.913514
num_epoch: 15, loss: 1.907323
num_epoch: 16, loss: 1.901224
num_epoch: 17, loss: 1.839411
num_epoch: 18, loss: 1.803628
num_epoch: 19, loss: 1.782827
num_epoch: 20, loss: 1.781178
num_epoch: 21, loss: 1.768686
num_epoch: 22, loss: 1.765548
num_epoch: 23, loss: 1.744351
num_epoch: 24, loss: 1.724888
num_epoch: 25, loss: 1.703979
num_epoch: 26, loss: 1.686251
num_epoch: 27, loss: 1.680252
num_epoch: 28, loss: 1.675609
num_epoch: 29, loss: 1.668216
num_epoch: 30, loss: 1.653882
num_epoch: 31, loss: 1.578463
num_epoch: 32, loss: 1.353604
num_epoch: 33, loss: 1.117105
num_epoch: 34, loss: 1.0491
num_epoch: 35, loss: 1.006742
num_epoch: 36, loss: 0.8498396
num_epoch: 37, loss: 0.7448646
num_epoch: 38, loss: 0.6722037
num_epoch: 39, loss: 0.4578193
num_epoch: 40, loss: 0.4108066
num_epoch: 41, loss: 0.4088068
num_epoch: 42, loss: 0.3846267
num_epoch: 43, loss: 0.3768285
num_epoch: 44, loss: 0.3741221
num_epoch: 45, loss: 0.3434927
num_epoch: 46, loss: 0.3317171
num_epoch: 47, loss: 0.3249993
num_epoch: 48, loss: 0.3196834
num_epoch: 49, loss: 0.3160568
num_epoch: 50, loss: 0.3131729
num_epoch: 51, loss: 0.3106357
num_epoch: 52, loss: 0.2849242
num_epoch: 53, loss: 0.2618929
num_epoch: 54, loss: 0.2536477
num_epoch: 55, loss: 0.2416837
num_epoch: 56, loss: 0.2288394
num_epoch: 57, loss: 0.2231531
num_epoch: 58, loss: 0.2163226
num_epoch: 59, loss: 0.2099124
num_epoch: 60, loss: 0.2056735
num_epoch: 61, loss: 0.2035462
num_epoch: 62, loss: 0.2029281
num_epoch: 63, loss: 0.2025963
num_epoch: 64, loss: 0.201955
num_epoch: 65, loss: 0.1999461
num_epoch: 66, loss: 0.1981866
num_epoch: 67, loss: 0.1969129
num_epoch: 68, loss: 0.1962111
num_epoch: 69, loss: 0.1956621
num_epoch: 70, loss: 0.1946721
num_epoch: 71, loss: 0.1915076
num_epoch: 72, loss: 0.1885416
num_epoch: 73, loss: 0.1853037
num_epoch: 74, loss: 0.1822084
num_epoch: 75, loss: 0.1773464
num_epoch: 76, loss: 0.1756983
num_epoch: 77, loss: 0.1739512
num_epoch: 78, loss: 0.1709671
num_epoch: 79, loss: 0.1699251
num_epoch: 80, loss: 0.1687213
num_epoch: 81, loss: 0.1671657
num_epoch: 82, loss: 0.1646283
num_epoch: 83, loss: 0.1612337
num_epoch: 84, loss: 0.1567707
num_epoch: 85, loss: 0.1525768
num_epoch: 86, loss: 0.1492088
num_epoch: 87, loss: 0.147417
num_epoch: 88, loss: 0.1465468
num_epoch: 89, loss: 0.1458401
num_epoch: 90, loss: 0.1443208
num_epoch: 91, loss: 0.1439579
num_epoch: 92, loss: 0.1432317
num_epoch: 93, loss: 0.1424719
num_epoch: 94, loss: 0.1421733
num_epoch: 95, loss: 0.1416409
num_epoch: 96, loss: 0.1407395
num_epoch: 97, loss: 0.1397397
num_epoch: 98, loss: 0.1387214
num_epoch: 99, loss: 0.1372793
num_epoch: 100, loss: 0.1360353

real    0m44.599s
user    1m16.818s
sys     0m30.569s
```
pytorch：
```
num_epoch: 1, loss: 14.48055
num_epoch: 2, loss: 4.667124
num_epoch: 3, loss: 2.576681
num_epoch: 4, loss: 2.270322
num_epoch: 5, loss: 2.092035
num_epoch: 6, loss: 2.058079
num_epoch: 7, loss: 2.000969
num_epoch: 8, loss: 1.9487
num_epoch: 9, loss: 1.885487
num_epoch: 10, loss: 1.632429
num_epoch: 11, loss: 1.521288
num_epoch: 12, loss: 1.210068
num_epoch: 13, loss: 0.9161879
num_epoch: 14, loss: 0.6901541
num_epoch: 15, loss: 0.5542452
num_epoch: 16, loss: 0.4754703
num_epoch: 17, loss: 0.4535766
num_epoch: 18, loss: 0.4168673
num_epoch: 19, loss: 0.3816084
num_epoch: 20, loss: 0.3575251
num_epoch: 21, loss: 0.3435943
num_epoch: 22, loss: 0.3248534
num_epoch: 23, loss: 0.3189998
num_epoch: 24, loss: 0.3065637
num_epoch: 25, loss: 0.2888044
num_epoch: 26, loss: 0.2737718
num_epoch: 27, loss: 0.264671
num_epoch: 28, loss: 0.2612346
num_epoch: 29, loss: 0.2547746
num_epoch: 30, loss: 0.2433318
num_epoch: 31, loss: 0.2219352
num_epoch: 32, loss: 0.2078502
num_epoch: 33, loss: 0.1914392
num_epoch: 34, loss: 0.1791755
num_epoch: 35, loss: 0.1765876
num_epoch: 36, loss: 0.1755987
num_epoch: 37, loss: 0.1719213
num_epoch: 38, loss: 0.1682622
num_epoch: 39, loss: 0.1619158
num_epoch: 40, loss: 0.1528487
num_epoch: 41, loss: 0.1411972
num_epoch: 42, loss: 0.128288
num_epoch: 43, loss: 0.1162378
num_epoch: 44, loss: 0.1082659
num_epoch: 45, loss: 0.1037716
num_epoch: 46, loss: 0.1021036
num_epoch: 47, loss: 0.09785821
num_epoch: 48, loss: 0.09681884
num_epoch: 49, loss: 0.09648045
num_epoch: 50, loss: 0.09544889
num_epoch: 51, loss: 0.09346515
num_epoch: 52, loss: 0.09155219
num_epoch: 53, loss: 0.0905012
num_epoch: 54, loss: 0.09023342
num_epoch: 55, loss: 0.09018737
num_epoch: 56, loss: 0.08972334
num_epoch: 57, loss: 0.08954569
num_epoch: 58, loss: 0.08914848
num_epoch: 59, loss: 0.08899262
num_epoch: 60, loss: 0.08862263
num_epoch: 61, loss: 0.08774682
num_epoch: 62, loss: 0.08730914
num_epoch: 63, loss: 0.0870278
num_epoch: 64, loss: 0.08620677
num_epoch: 65, loss: 0.08576062
num_epoch: 66, loss: 0.08567091
num_epoch: 67, loss: 0.08559363
num_epoch: 68, loss: 0.08553697
num_epoch: 69, loss: 0.08550375
num_epoch: 70, loss: 0.08540776
num_epoch: 71, loss: 0.08524579
num_epoch: 72, loss: 0.08510602
num_epoch: 73, loss: 0.08482966
num_epoch: 74, loss: 0.08473272
num_epoch: 75, loss: 0.08461963
num_epoch: 76, loss: 0.08449384
num_epoch: 77, loss: 0.08425471
num_epoch: 78, loss: 0.08395718
num_epoch: 79, loss: 0.08385325
num_epoch: 80, loss: 0.08377442
num_epoch: 81, loss: 0.08359905
num_epoch: 82, loss: 0.08309891
num_epoch: 83, loss: 0.08292507
num_epoch: 84, loss: 0.08278128
num_epoch: 85, loss: 0.08252225
num_epoch: 86, loss: 0.08221992
num_epoch: 87, loss: 0.08210817
num_epoch: 88, loss: 0.0819231
num_epoch: 89, loss: 0.08170464
num_epoch: 90, loss: 0.08162272
num_epoch: 91, loss: 0.08124812
num_epoch: 92, loss: 0.08081728
num_epoch: 93, loss: 0.08041939
num_epoch: 94, loss: 0.07985346
num_epoch: 95, loss: 0.07928944
num_epoch: 96, loss: 0.07875808
num_epoch: 97, loss: 0.07850216
num_epoch: 98, loss: 0.07829909
num_epoch: 99, loss: 0.07827684
num_epoch: 100, loss: 0.0781415

real    0m42.594s
user    0m41.285s
sys     0m1.285s
```

**Comment by levi131** [comment]
需要在oneflow代码仓中补充测试验证，分别验证使用strong wolf和不使用strong wolf的情况

**Comment by L-Xiafeng** [comment]
oneflow,strong_wolfe训练结果
```
num_epoch: 100, loss: 0.09013008

real    1m17.526s
user    2m24.450s
sys     0m50.515s
```
torch,strong_wolfe训练结果
```
num_epoch: 100, loss: 0.09780428

real    1m10.364s
user    1m9.138s
sys     0m5.576s
```

**Comment by L-Xiafeng** [comment]
1000epoch稳定性测试

| 框架    | allow_tf32 | allow_fp16_reduced | 线搜索方法 | RTX3090结果 | RTX2080Ti结果 |
| ------- | :---------------- | ------------------ | ---------- | ---- | ---- |
| oneflow | False             | False              | None       | OK   | OK |
| oneflow | False             | True               | None       | OK | OK |
| oneflow | True              | False              | None       | 会训飞 | OK |
| oneflow | True              | True               | Nonel      | 会训飞          | OK |
| oneflow | False             | False              | Strong_wolfe       | OK   | OK |
| oneflow | False             | True               | Strong_wolfe       | OK | OK |
| oneflow | True              | False              | Strong_wolfe       | loss卡在0.27 | OK |
| oneflow | True              | True               | Strong_wolfe       | loss卡在0.27 | OK |
| torch | False             | False              | None       | OK | OK |
| torch | False             | True               | None       | OK | OK |
| torch | True              | False              | None       | loss为nan | OK |
| torch | True              | True               | None       | loss为nan | OK |
| torch | False             | False              | Strong_wolfe       | loss卡死在0.107 | OK |
| torch | False             | True               | Strong_wolfe       | loss卡死在0.107 | OK |
| torch | True              | False              | Strong_wolfe       | loss卡死在2.39  | OK            |
| torch | True              | True               | Strong_wolfe   | loss卡死在2.39  | OK            |

**Review by levi131 — APPROVED** [review]
LGTM

**Review by Yang-lin-09 — APPROVED** [review]

**Pull request merged**
