### PR TITLE
fix missing link for bert model

### PR DESCRIPTION
**Pull request by jsonlee0x01**

### CODE REVIEW

**Review by lijiansong — APPROVED** [review]

**Comment by jsonlee0x01** [comment]
@lixinqi Plz, review required :-)

**Comment by daquexian** [comment]
looks like the url should be https://github.com/Oneflow-Inc/models/tree/main/NLP/BERT instead. @Ldpe2G could you please confirm it?

**Comment by Ldpe2G** [comment]
> looks like the url should be https://github.com/Oneflow-Inc/models/tree/main/NLP/BERT instead. @Ldpe2G could you please confirm it?

Yes, it should be: https://github.com/Oneflow-Inc/models/tree/main/NLP/BERT

**Comment by daquexian** [comment]
> > looks like the url should be https://github.com/Oneflow-Inc/models/tree/main/NLP/BERT instead. @Ldpe2G could you please confirm it?
> 
> Yes, it should be: https://github.com/Oneflow-Inc/models/tree/main/NLP/BERT

@jsonlee0x01 @lijiansong Could you please update the pr? [Oneflow-Benchmark](https://github.com/Oneflow-Inc/OneFlow-Benchmark) is an old repo and [models](https://github.com/Oneflow-Inc/models) is the actively maintained one.

**Comment by jsonlee0x01** [comment]
OK

**Pull request closed without merging**
