### PR TITLE
Nhwc merge

### PR DESCRIPTION
**Pull request by strint**
just for perf

### CODE REVIEW

**Comment by ouyangyu** [comment]
<p align="center">表 2021-11-29 ResNet50 ddp  dlperf 运行结果</p>

|                                         | [aa7a9ff](https://github.com/Oneflow-Inc/oneflow/commit/aa7a9ff) |
| :-------------------------------------: | :----------------------------------------------------------: |
|                                         |                    Memory/Throughput                         |
| ResNet50_ddp_dlperf_cpudecode_FP32_b256_1n1g | 27258 MiB / [276.76](https://oneflow-test.oss-cn-beijing.aliyuncs.com/OneBrain/commit/nhwc_merge/20211129/aa7a9ff/ResNet50-ddp/dlperf/1n1g/resnet50_ddp_DCcpu_FP32_b256_1n1g_nhwc_merge_20211129_103857761754758.log) |


<p align="center">表 2021-11-29 ResNet50 graph  dlperf 运行结果</p>

|                                         | [aa7a9ff](https://github.com/Oneflow-Inc/oneflow/commit/aa7a9ff) |
| :-------------------------------------: | :----------------------------------------------------------: |
|                                         |                    Memory/Throughput                         |
| ResNet50_graph_dlperf_cpudecode_FP16_b512_1n1g | 23158 MiB / [877.05](https://oneflow-test.oss-cn-beijing.aliyuncs.com/OneBrain/commit/nhwc_merge/20211129/aa7a9ff/ResNet50-graph/dlperf/1n1g/resnet50_graph_DCcpu_FP16_b512_1n1g_nhwc_merge_20211129_103514345411466.log) |
| ResNet50_graph_dlperf_cpudecode_FP32_b256_1n1g | None MiB / [0](https://oneflow-test.oss-cn-beijing.aliyuncs.com/OneBrain/commit/nhwc_merge/20211129/aa7a9ff/ResNet50-graph/dlperf/1n1g/resnet50_graph_DCcpu_FP32_b256_1n1g_nhwc_merge_20211129_103846225136331.log) |
| ResNet50_graph_dlperf_gpudecode_FP16_b512_1n1g | 23852 MiB / [1175.08](https://oneflow-test.oss-cn-beijing.aliyuncs.com/OneBrain/commit/nhwc_merge/20211129/aa7a9ff/ResNet50-graph/dlperf/1n1g/resnet50_graph_DCgpu_FP16_b512_1n1g_nhwc_merge_20211129_103218039166147.log) |
| ResNet50_graph_dlperf_gpudecode_FP32_b256_1n1g | None MiB / [0](https://oneflow-test.oss-cn-beijing.aliyuncs.com/OneBrain/commit/nhwc_merge/20211129/aa7a9ff/ResNet50-graph/dlperf/1n1g/resnet50_graph_DCgpu_FP32_b256_1n1g_nhwc_merge_20211129_103503177488730.log) |


<p align="center">表 2021-11-29 ResNet50 lazy  dlperf 运行结果</p>

|                                         | [aa7a9ff](https://github.com/Oneflow-Inc/oneflow/commit/aa7a9ff) |
| :-------------------------------------: | :----------------------------------------------------------: |
|                                         |                    Memory/Throughput                         |
| ResNet50_lazy_dlperf_gpudecode_FP16_b512_1n1g | 24126 MiB / [1191.676](https://oneflow-test.oss-cn-beijing.aliyuncs.com/OneBrain/commit/nhwc_merge/20211129/aa7a9ff/ResNet50-lazy/dlperf/1n1g/resnet50_lazy_FP16_b512_1n1g_nhwc_merge_20211129_104343586431371.log) |
| ResNet50_lazy_dlperf_cpudecode_FP16_b512_1n1g | 23332 MiB / [1198.7](https://oneflow-test.oss-cn-beijing.aliyuncs.com/OneBrain/commit/nhwc_merge/20211129/aa7a9ff/ResNet50-lazy/dlperf/1n1g/resnet50_lazy_FP16_b512_1n1g_nhwc_merge_20211129_104649993196498.log) |
| ResNet50_lazy_dlperf_gpudecode_FP32_b256_1n1g | None MiB / [0](https://oneflow-test.oss-cn-beijing.aliyuncs.com/OneBrain/commit/nhwc_merge/20211129/aa7a9ff/ResNet50-lazy/dlperf/1n1g/resnet50_lazy_FP32_b256_1n1g_nhwc_merge_20211129_104636494882373.log) |
| ResNet50_lazy_dlperf_cpudecode_FP32_b256_1n1g | None MiB / [0](https://oneflow-test.oss-cn-beijing.aliyuncs.com/OneBrain/commit/nhwc_merge/20211129/aa7a9ff/ResNet50-lazy/dlperf/1n1g/resnet50_lazy_FP32_b256_1n1g_nhwc_merge_20211129_104942459048971.log) |

fp32显存太大。fp16性能都明显下降。

**Comment by ouyangyu** [comment]
<p align="center">表 2021-11-29 ResNet50 ddp  dlperf 运行结果</p>

|                                         | [cabe807](https://github.com/Oneflow-Inc/oneflow/commit/cabe807) |
| :-------------------------------------: | :----------------------------------------------------------: |
|                                         |                    Memory/Throughput                         |
| ResNet50_ddp_dlperf_cpudecode_FP32_b256_1n1g | 27258 MiB / [265.59](https://oneflow-test.oss-cn-beijing.aliyuncs.com/OneBrain/commit/nhwc_merge/20211129/cabe807/ResNet50-ddp/dlperf/1n1g/resnet50_ddp_DCcpu_FP32_b256_1n1g_nhwc_merge_20211129_170146709831379.log) |


<p align="center">表 2021-11-29 ResNet50 ddp  nsys 运行结果</p>

| [cabe807](https://github.com/Oneflow-Inc/oneflow/commit/cabe807) |
| :----------------------------------------------------------: |
| [ResNet50_ddp_nsys_cpudecode_FP32_b256_1n1g](https://oneflow-test.oss-cn-beijing.aliyuncs.com/OneBrain/commit/nhwc_merge/20211129/cabe807/ResNet50-ddp/nsys/1n1g/resnet50_ddp_DCcpu_FP32_b256_1n1g_nhwc_merge_20211129_171607927973760.qdrep) |


<p align="center">表 2021-11-29 ResNet50 graph  dlperf 运行结果</p>

|                                         | [cabe807](https://github.com/Oneflow-Inc/oneflow/commit/cabe807) |
| :-------------------------------------: | :----------------------------------------------------------: |
|                                         |                    Memory/Throughput                         |
| ResNet50_graph_dlperf_cpudecode_FP16_b512_1n1g | 22910 MiB / [1005.87](https://oneflow-test.oss-cn-beijing.aliyuncs.com/OneBrain/commit/nhwc_merge/20211129/cabe807/ResNet50-graph/dlperf/1n1g/resnet50_graph_DCcpu_FP16_b512_1n1g_nhwc_merge_20211129_165825596078550.log) |
| ResNet50_graph_dlperf_cpudecode_FP32_b256_1n1g | None MiB / [0](https://oneflow-test.oss-cn-beijing.aliyuncs.com/OneBrain/commit/nhwc_merge/20211129/cabe807/ResNet50-graph/dlperf/1n1g/resnet50_graph_DCcpu_FP32_b256_1n1g_nhwc_merge_20211129_170135305681427.log) |
| ResNet50_graph_dlperf_gpudecode_FP16_b512_1n1g | 23590 MiB / [1362.33](https://oneflow-test.oss-cn-beijing.aliyuncs.com/OneBrain/commit/nhwc_merge/20211129/cabe807/ResNet50-graph/dlperf/1n1g/resnet50_graph_DCgpu_FP16_b512_1n1g_nhwc_merge_20211129_165548434578094.log) |
| ResNet50_graph_dlperf_gpudecode_FP32_b256_1n1g | None MiB / [0](https://oneflow-test.oss-cn-beijing.aliyuncs.com/OneBrain/commit/nhwc_merge/20211129/cabe807/ResNet50-graph/dlperf/1n1g/resnet50_graph_DCgpu_FP32_b256_1n1g_nhwc_merge_20211129_165815498319572.log) |


<p align="center">表 2021-11-29 ResNet50 graph  nsys 运行结果</p>

| [cabe807](https://github.com/Oneflow-Inc/oneflow/commit/cabe807) |
| :----------------------------------------------------------: |
| [ResNet50_graph_nsys_cpudecode_FP16_b512_1n1g](https://oneflow-test.oss-cn-beijing.aliyuncs.com/OneBrain/commit/nhwc_merge/20211129/cabe807/ResNet50-graph/nsys/1n1g/resnet50_graph_DCcpu_FP16_b512_1n1g_nhwc_merge_20211129_171425111930175.qdrep) |
| [ResNet50_graph_nsys_cpudecode_FP32_b256_1n1g](https://oneflow-test.oss-cn-beijing.aliyuncs.com/OneBrain/commit/nhwc_merge/20211129/cabe807/ResNet50-graph/nsys/1n1g/resnet50_graph_DCcpu_FP32_b256_1n1g_nhwc_merge_20211129_171539449163439.qdrep) |
| [ResNet50_graph_nsys_gpudecode_FP16_b512_1n1g](https://oneflow-test.oss-cn-beijing.aliyuncs.com/OneBrain/commit/nhwc_merge/20211129/cabe807/ResNet50-graph/nsys/1n1g/resnet50_graph_DCgpu_FP16_b512_1n1g_nhwc_merge_20211129_171247679574634.qdrep) |
| [ResNet50_graph_nsys_gpudecode_FP32_b256_1n1g](https://oneflow-test.oss-cn-beijing.aliyuncs.com/OneBrain/commit/nhwc_merge/20211129/cabe807/ResNet50-graph/nsys/1n1g/resnet50_graph_DCgpu_FP32_b256_1n1g_nhwc_merge_20211129_171404919515694.qdrep) |


<p align="center">表 2021-11-29 ResNet50 lazy  dlperf 运行结果</p>

|                                         | [cabe807](https://github.com/Oneflow-Inc/oneflow/commit/cabe807) |
| :-------------------------------------: | :----------------------------------------------------------: |
|                                         |                    Memory/Throughput                         |
| ResNet50_lazy_dlperf_gpudecode_FP16_b512_1n1g | 23846 MiB / [1411.089](https://oneflow-test.oss-cn-beijing.aliyuncs.com/OneBrain/commit/nhwc_merge/20211129/cabe807/ResNet50-lazy/dlperf/1n1g/resnet50_lazy_FP16_b512_1n1g_nhwc_merge_20211129_170643559653055.log) |
| ResNet50_lazy_dlperf_cpudecode_FP16_b512_1n1g | 23084 MiB / [1428.246](https://oneflow-test.oss-cn-beijing.aliyuncs.com/OneBrain/commit/nhwc_merge/20211129/cabe807/ResNet50-lazy/dlperf/1n1g/resnet50_lazy_FP16_b512_1n1g_nhwc_merge_20211129_170933927524720.log) |
| ResNet50_lazy_dlperf_gpudecode_FP32_b256_1n1g | None MiB / [0](https://oneflow-test.oss-cn-beijing.aliyuncs.com/OneBrain/commit/nhwc_merge/20211129/cabe807/ResNet50-lazy/dlperf/1n1g/resnet50_lazy_FP32_b256_1n1g_nhwc_merge_20211129_170920276209285.log) |
| ResNet50_lazy_dlperf_cpudecode_FP32_b256_1n1g | None MiB / [0](https://oneflow-test.oss-cn-beijing.aliyuncs.com/OneBrain/commit/nhwc_merge/20211129/cabe807/ResNet50-lazy/dlperf/1n1g/resnet50_lazy_FP32_b256_1n1g_nhwc_merge_20211129_171209981448681.log) |


<p align="center">表 2021-11-29 ResNet50 lazy  nsys 运行结果</p>

| [cabe807](https://github.com/Oneflow-Inc/oneflow/commit/cabe807) |
| :----------------------------------------------------------: |
| [ResNet50_lazy_nsys_gpudecode_FP16_b512_1n1g](https://oneflow-test.oss-cn-beijing.aliyuncs.com/OneBrain/commit/nhwc_merge/20211129/cabe807/ResNet50-lazy/nsys/1n1g/resnet50_lazy_FP16_b512_1n1g_nhwc_merge_20211129_171847110171637.qdrep) |
| [ResNet50_lazy_nsys_cpudecode_FP16_b512_1n1g](https://oneflow-test.oss-cn-beijing.aliyuncs.com/OneBrain/commit/nhwc_merge/20211129/cabe807/ResNet50-lazy/nsys/1n1g/resnet50_lazy_FP16_b512_1n1g_nhwc_merge_20211129_172033918102154.qdrep) |
| [ResNet50_lazy_nsys_gpudecode_FP32_b256_1n1g](https://oneflow-test.oss-cn-beijing.aliyuncs.com/OneBrain/commit/nhwc_merge/20211129/cabe807/ResNet50-lazy/nsys/1n1g/resnet50_lazy_FP32_b256_1n1g_nhwc_merge_20211129_172008605590647.qdrep) |
| [ResNet50_lazy_nsys_cpudecode_FP32_b256_1n1g](https://oneflow-test.oss-cn-beijing.aliyuncs.com/OneBrain/commit/nhwc_merge/20211129/cabe807/ResNet50-lazy/nsys/1n1g/resnet50_lazy_FP32_b256_1n1g_nhwc_merge_20211129_172154255060296.qdrep) |

fp32情况下内存增大。cpudecode在graph fp16下性能有提升

**Comment by ouyangyu** [comment]
<p align="center">表 2021-11-30 ResNet50 ddp  dlperf 运行结果</p>

|                                         | [58d8d27](https://github.com/Oneflow-Inc/oneflow/commit/58d8d27) |
| :-------------------------------------: | :----------------------------------------------------------: |
|                                         |                    Memory/Throughput                         |
| ResNet50_ddp_dlperf_cpudecode_FP32_b256_1n1g | 27258 MiB / [270.05](https://oneflow-test.oss-cn-beijing.aliyuncs.com/OneBrain/commit/nhwc_merge/20211130/58d8d27/ResNet50-ddp/dlperf/1n1g/resnet50_ddp_DCcpu_FP32_b256_1n1g_nhwc_merge_20211130_094814207384132.log) |


<p align="center">表 2021-11-30 ResNet50 ddp  nsys 运行结果</p>

| [58d8d27](https://github.com/Oneflow-Inc/oneflow/commit/58d8d27) |
| :----------------------------------------------------------: |
| [ResNet50_ddp_nsys_cpudecode_FP32_b256_1n1g](https://oneflow-test.oss-cn-beijing.aliyuncs.com/OneBrain/commit/nhwc_merge/20211130/58d8d27/ResNet50-ddp/nsys/1n1g/resnet50_ddp_DCcpu_FP32_b256_1n1g_nhwc_merge_20211130_101159905276686.qdrep) |


<p align="center">表 2021-11-30 ResNet50 graph  dlperf 运行结果</p>

|                                         | [58d8d27](https://github.com/Oneflow-Inc/oneflow/commit/58d8d27) |
| :-------------------------------------: | :----------------------------------------------------------: |
|                                         |                    Memory/Throughput                         |
| ResNet50_graph_dlperf_cpudecode_FP16_b512_1n1g | 22910 MiB / [998.66](https://oneflow-test.oss-cn-beijing.aliyuncs.com/OneBrain/commit/nhwc_merge/20211130/58d8d27/ResNet50-graph/dlperf/1n1g/resnet50_graph_DCcpu_FP16_b512_1n1g_nhwc_merge_20211130_094126695758675.log) |
| ResNet50_graph_dlperf_cpudecode_FP32_b256_1n1g | 23020 MiB / [384.25](https://oneflow-test.oss-cn-beijing.aliyuncs.com/OneBrain/commit/nhwc_merge/20211130/58d8d27/ResNet50-graph/dlperf/1n1g/resnet50_graph_DCcpu_FP32_b256_1n1g_nhwc_merge_20211130_094439524052306.log) |
| ResNet50_graph_dlperf_gpudecode_FP16_b512_1n1g | 23624 MiB / [1394.76](https://oneflow-test.oss-cn-beijing.aliyuncs.com/OneBrain/commit/nhwc_merge/20211130/58d8d27/ResNet50-graph/dlperf/1n1g/resnet50_graph_DCgpu_FP16_b512_1n1g_nhwc_merge_20211130_093525097242032.log) |
| ResNet50_graph_dlperf_gpudecode_FP32_b256_1n1g | 23650 MiB / [380.88](https://oneflow-test.oss-cn-beijing.aliyuncs.com/OneBrain/commit/nhwc_merge/20211130/58d8d27/ResNet50-graph/dlperf/1n1g/resnet50_graph_DCgpu_FP32_b256_1n1g_nhwc_merge_20211130_093751302439313.log) |


<p align="center">表 2021-11-30 ResNet50 graph  nsys 运行结果</p>

| [58d8d27](https://github.com/Oneflow-Inc/oneflow/commit/58d8d27) |
| :----------------------------------------------------------: |
| [ResNet50_graph_nsys_cpudecode_FP16_b512_1n1g](https://oneflow-test.oss-cn-beijing.aliyuncs.com/OneBrain/commit/nhwc_merge/20211130/58d8d27/ResNet50-graph/nsys/1n1g/resnet50_graph_DCcpu_FP16_b512_1n1g_nhwc_merge_20211130_100854094875775.qdrep) |
| [ResNet50_graph_nsys_cpudecode_FP32_b256_1n1g](https://oneflow-test.oss-cn-beijing.aliyuncs.com/OneBrain/commit/nhwc_merge/20211130/58d8d27/ResNet50-graph/nsys/1n1g/resnet50_graph_DCcpu_FP32_b256_1n1g_nhwc_merge_20211130_101006750147318.qdrep) |
| [ResNet50_graph_nsys_gpudecode_FP16_b512_1n1g](https://oneflow-test.oss-cn-beijing.aliyuncs.com/OneBrain/commit/nhwc_merge/20211130/58d8d27/ResNet50-graph/nsys/1n1g/resnet50_graph_DCgpu_FP16_b512_1n1g_nhwc_merge_20211130_100556908257997.qdrep) |
| [ResNet50_graph_nsys_gpudecode_FP32_b256_1n1g](https://oneflow-test.oss-cn-beijing.aliyuncs.com/OneBrain/commit/nhwc_merge/20211130/58d8d27/ResNet50-graph/nsys/1n1g/resnet50_graph_DCgpu_FP32_b256_1n1g_nhwc_merge_20211130_100715678589770.qdrep) |


<p align="center">表 2021-11-30 ResNet50 lazy  dlperf 运行结果</p>

|                                         | [58d8d27](https://github.com/Oneflow-Inc/oneflow/commit/58d8d27) |
| :-------------------------------------: | :----------------------------------------------------------: |
|                                         |                    Memory/Throughput                         |
| ResNet50_lazy_dlperf_gpudecode_FP16_b512_1n1g | 23864 MiB / [1408.221](https://oneflow-test.oss-cn-beijing.aliyuncs.com/OneBrain/commit/nhwc_merge/20211130/58d8d27/ResNet50-lazy/dlperf/1n1g/resnet50_lazy_FP16_b512_1n1g_nhwc_merge_20211130_095307234275559.log) |
| ResNet50_lazy_dlperf_cpudecode_FP16_b512_1n1g | 23084 MiB / [1410.295](https://oneflow-test.oss-cn-beijing.aliyuncs.com/OneBrain/commit/nhwc_merge/20211130/58d8d27/ResNet50-lazy/dlperf/1n1g/resnet50_lazy_FP16_b512_1n1g_nhwc_merge_20211130_095927056216681.log) |
| ResNet50_lazy_dlperf_gpudecode_FP32_b256_1n1g | 23402 MiB / [383.565](https://oneflow-test.oss-cn-beijing.aliyuncs.com/OneBrain/commit/nhwc_merge/20211130/58d8d27/ResNet50-lazy/dlperf/1n1g/resnet50_lazy_FP32_b256_1n1g_nhwc_merge_20211130_095543719892507.log) |
| ResNet50_lazy_dlperf_cpudecode_FP32_b256_1n1g | 22714 MiB / [385.337](https://oneflow-test.oss-cn-beijing.aliyuncs.com/OneBrain/commit/nhwc_merge/20211130/58d8d27/ResNet50-lazy/dlperf/1n1g/resnet50_lazy_FP32_b256_1n1g_nhwc_merge_20211130_100203234106805.log) |


<p align="center">表 2021-11-30 ResNet50 lazy  nsys 运行结果</p>

| [58d8d27](https://github.com/Oneflow-Inc/oneflow/commit/58d8d27) |
| :----------------------------------------------------------: |
| [ResNet50_lazy_nsys_gpudecode_FP16_b512_1n1g](https://oneflow-test.oss-cn-beijing.aliyuncs.com/OneBrain/commit/nhwc_merge/20211130/58d8d27/ResNet50-lazy/nsys/1n1g/resnet50_lazy_FP16_b512_1n1g_nhwc_merge_20211130_101432573183624.qdrep) |
| [ResNet50_lazy_nsys_cpudecode_FP16_b512_1n1g](https://oneflow-test.oss-cn-beijing.aliyuncs.com/OneBrain/commit/nhwc_merge/20211130/58d8d27/ResNet50-lazy/nsys/1n1g/resnet50_lazy_FP16_b512_1n1g_nhwc_merge_20211130_101652052902912.qdrep) |
| [ResNet50_lazy_nsys_gpudecode_FP32_b256_1n1g](https://oneflow-test.oss-cn-beijing.aliyuncs.com/OneBrain/commit/nhwc_merge/20211130/58d8d27/ResNet50-lazy/nsys/1n1g/resnet50_lazy_FP32_b256_1n1g_nhwc_merge_20211130_101554293611287.qdrep) |
| [ResNet50_lazy_nsys_cpudecode_FP32_b256_1n1g](https://oneflow-test.oss-cn-beijing.aliyuncs.com/OneBrain/commit/nhwc_merge/20211130/58d8d27/ResNet50-lazy/nsys/1n1g/resnet50_lazy_FP32_b256_1n1g_nhwc_merge_20211130_101813174148618.qdrep) |

cpudecode_FP16_性能有所提升

**Comment by strint** [comment]
> 

- cpu的性能提升主要来自对断流的缓解，dataloader可以超前触发
  -  vm的的调度
  - src subset tick 对 ouput 的控制边register改为2

另外之前出现的内存oom问题，是把所有控制边改成2导致的，去掉这个修改就可以解决内存翻倍问题。

**Comment by ouyangyu** [comment]
- 1000iter打印一次结果

<p align="center">表 2021-11-30 ResNet50 graph  dlperf 运行结果</p>

|                                         | [58d8d27](https://github.com/Oneflow-Inc/oneflow/commit/58d8d27) |
| :-------------------------------------: | :----------------------------------------------------------: |
|                                         |                    Memory/Throughput                         |
| ResNet50_graph_dlperf_cpudecode_FP16_b512_1n1g | 22910 MiB / [1007.47](https://oneflow-test.oss-cn-beijing.aliyuncs.com/OneBrain/commit/nhwc_merge_1000/20211130/58d8d27/ResNet50-graph/dlperf/1n1g/resnet50_graph_DCcpu_FP16_b512_1n1g_nhwc_merge_1000_20211130_172031040449574.log) |
| ResNet50_graph_dlperf_gpudecode_FP16_b512_1n1g | 23608 MiB / [1377.39](https://oneflow-test.oss-cn-beijing.aliyuncs.com/OneBrain/commit/nhwc_merge_1000/20211130/58d8d27/ResNet50-graph/dlperf/1n1g/resnet50_graph_DCgpu_FP16_b512_1n1g_nhwc_merge_1000_20211130_170654169943625.log) |



<p align="center">表 2021-11-30 ResNet50 lazy  dlperf 运行结果</p>

|                                         | [58d8d27](https://github.com/Oneflow-Inc/oneflow/commit/58d8d27) |
| :-------------------------------------: | :----------------------------------------------------------: |
|                                         |                    Memory/Throughput                         |
| ResNet50_lazy_dlperf_gpudecode_FP16_b512_1n1g | 23868 MiB / [1402.443](https://oneflow-test.oss-cn-beijing.aliyuncs.com/OneBrain/commit/nhwc_merge_1000/20211130/58d8d27/ResNet50-lazy/dlperf/1n1g/resnet50_lazy_FP16_b512_1n1g_nhwc_merge_1000_20211130_174235895400596.log) |
| ResNet50_lazy_dlperf_cpudecode_FP16_b512_1n1g | 23084 MiB / [1417.809](https://oneflow-test.oss-cn-beijing.aliyuncs.com/OneBrain/commit/nhwc_merge_1000/20211130/58d8d27/ResNet50-lazy/dlperf/1n1g/resnet50_lazy_FP16_b512_1n1g_nhwc_merge_1000_20211130_175609596221236.log) |

从上述结果来看，print loss导致吞吐量下降问题，不明显

**Pull request closed without merging**
