### PR TITLE
fix the usage of argument end_factor in LinearLR

### PR DESCRIPTION
**Pull request by basicv8vc**
In `LinearLR`, when `last_step` >= `total_iters`,

```
lr = base_lr * 1.
```

to be consistent with pytorch

```
lr = base_lr * end_factor

```

related issue https://github.com/Oneflow-Inc/oneflow/issues/8343

### CODE REVIEW

**Comment by leaves-zwx** [comment]
Thanks for the fix in this pull request, it looks good to me. I will approve it which will be auto-merged to master.

**Review by leaves-zwx — APPROVED** [review]

**Review by doombeaker — APPROVED** [review]

**Comment by doombeaker** [comment]
The CI failed for code not formatted correctly.
Can you please run `ninja of_format` or `make of_format` for re-formating the code and then push it?

**Comment by jackalcooper** [comment]
hi @basicv8vc 
- please allow author editing like [this](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/working-with-forks/allowing-changes-to-a-pull-request-branch-created-from-a-fork)
- or download and apply the formatting patch [here](https://github.com/Oneflow-Inc/oneflow/actions/runs/3006093816) and apply locally and push

**Comment by leaves-zwx** [comment]
Thanks for the fix. I will merge it by a new PR https://github.com/Oneflow-Inc/oneflow/pull/9421.

**Pull request closed without merging**
