### PR TITLE
upgrade XRT XLA to TF 2.3.0

### PR DESCRIPTION
**Pull request by jackalcooper**
- tf 升级到 2.3.0，做了一些修改，已经成功编译
- tf 2.3.0 在 gcc 4.8 编译失败，升级到了 7.3 （官方发布包也是用 7.3），后续考虑 oneflow 发布也用 7.3，不然带不了 xla 了
- tf 2.3.0 也需要更新版本的 bazel（3以上），之前的不好使了
- 受到 eigen 下载链接的影响，oneflow 无法编译。

### CODE REVIEW

**Comment by jackalcooper** [comment]
在 github 查看更新之后的 patch：
https://github.com/Oneflow-Inc/tensorflow/compare/v2.3.0...Oneflow-Inc:1f_dep_v2.3.0?expand=1

**Comment by yuanms2** [comment]
能不能修改成不是那种打patch，tensorflow原封不动，我们在oneflow里添加点代码来搞定。

**Comment by jackalcooper** [comment]
> 能不能修改成不是那种打patch，tensorflow原封不动，我们在oneflow里添加点代码来搞定。

我觉得是有可能的。

**Comment by yuanms2** [comment]
> > 能不能修改成不是那种打patch，tensorflow原封不动，我们在oneflow里添加点代码来搞定。
> 
> 我觉得是有可能的。

我问问陈后江，当时有没有考虑过把xla_runtime_util.h/cc 放在oneflow里面，而不是放在tensorflow里面。当时通过patch方式做有什么考虑，是不是有什么坑。

**Comment by yuanms2** [comment]
陈后江：“当时是因为这个patch的代码依赖了xla内部的代码，tensorflow在编译的时候把内部模块接口隐藏了。如果不和tensorflow一起编译，而是直接依赖tensorflow，则需要改一下bazel的编译选项，将相关的接口暴露出来。”，“最新的tensorflow可以看看有没有暴露出这些接口”

**Comment by qianzhang613** [comment]
when build with branch `dev_xla_tf_230`
```
CMake Error at cmake/third_party/tensorflow.cmake:106 (foreach):  
   Unknown argument:    
  ZIP_LISTS
```
Did there are CMake version depends?

**Comment by jackalcooper** [comment]
> ZIP_LISTS

Probably. Please use cmake 3.14 if possible. You could download version 3.14 from here: [https://github.com/Kitware/CMake/releases/download/v3.14.0/cmake-3.14.0-Linux-x86_64.tar.gz](https://github.com/Kitware/CMake/releases/download/v3.14.0/cmake-3.14.0-Linux-x86_64.tar.gz)

**Comment by qianzhang613** [comment]
> > ZIP_LISTS
> 
> Probably. Please use cmake 3.14 if possible. You could download pre-compiled version 3.14 from here: https://github.com/Kitware/CMake/releases/download/v3.14.0/cmake-3.14.0-Linux-x86_64.tar.gz

@jackalcooper  i can't find where is the `ZIP_LISTS` define?  Is there some code didnot push~~~ i guess~

**Comment by jackalcooper** [comment]
> `ZIP_LISTS`

I'm sorry. It requires cmake 3.17.4+ to support `ZIP_LISTS`

**Review by guo-ran — APPROVED** [review]

**Comment by jackalcooper** [comment]
@qianzhang613 you may use this link to install oneflow with XLA:
```
python3 -m pip install --find-links https://oneflow-inc.github.io/beta oneflow_cu102_xla --user
```

**Comment by qianzhang613** [comment]
there is coredump when build with `master`, but it is ok run without ` --use_xla`

cmd:
```
python3 -u of_cnn_train_val.py  \
    --train_data_dir=/youtu-public/imagenet/ofrecord/train --train_data_part_num=256 \
    --val_data_dir=/youtu-public/imagenet/ofrecord/val --val_data_part_num=256 \
    --gpu_num_per_node=8 \
    --model_update="momentum" \
    --learning_rate=0.256 \
    --loss_print_every_n_iter=100 \
    --batch_size_per_device=256 \
    --val_batch_size_per_device=256 \
    --num_epoch=90 \
    --model="resnet50" \
    --log_dir=./task_out \
    --node_ips=$NODE_IP_LIST \
    --num_nodes=$NODE_SIZE   --use_xla --use_fp16
```
coredump:
```
(gdb) bt
#0  0x00007ff6eb09f4a8 in xla::gpu::EnforceMinorToMajorReduceOpVisitor::HandleReduce(xla::HloInstruction*) () from /oneflow/third_party/tensorflow/lib/libxla_core.so
#1  0x00007ff6ed295b0d in tensorflow::Status xla::HloInstruction::Visit<xla::HloInstruction*>(xla::DfsHloVisitorBase<xla::HloInstruction*>*) ()
   from /oneflow/third_party/tensorflow/lib/libxla_core.so
#2  0x00007ff6ed2ab810 in tensorflow::Status xla::PostOrderDFS<xla::DfsHloVisitorBase<xla::HloInstruction*> >(xla::HloInstruction*, xla::DfsHloVisitorBase<xla::HloInstruction*>*, std::function<bool (std::pair<int, xla::HloInstruction const*>, std::pair<int, xla::HloInstruction const*>)> const*, bool) () from /oneflow/third_party/tensorflow/lib/libxla_core.so
#3  0x00007ff6ed2ac728 in tensorflow::Status xla::HloInstruction::Accept<xla::HloInstruction*>(xla::DfsHloVisitorBase<xla::HloInstruction*>*, bool, bool) ()
   from /oneflow/third_party/tensorflow/lib/libxla_core.so
#4  0x00007ff700b35721 in tensorflow::Status xla::HloComputation::Accept<xla::HloInstruction*>(xla::DfsHloVisitorBase<xla::HloInstruction*>*) const ()
   from /oneflow/build/python_scripts/oneflow/_oneflow_internal.cpython-36m-x86_64-linux-gnu.so
#5  0x00007ff6eb09ea93 in xla::gpu::ReductionLayoutNormalizer::Run(xla::HloModule*) () from /oneflow/third_party/tensorflow/lib/libxla_core.so
#6  0x00007ff6ebfd81f6 in stream_executor::port::StatusOr<bool> xla::HloPassPipeline::RunPassesInternal<xla::HloModule>(xla::HloModule*, absl::lts_2020_02_25::Span<xla::HloPassInterface* const>)
    () from /oneflow/third_party/tensorflow/lib/libxla_core.so
#7  0x00007ff6ebfd8c0a in xla::HloPassPipeline::Run(xla::HloModule*) () from /oneflow/third_party/tensorflow/lib/libxla_core.so
#8  0x00007ff6eaeb3b63 in xla::gpu::GpuCompiler::OptimizeHloPostLayoutAssignment(xla::HloModule*, stream_executor::StreamExecutor*, stream_executor::DeviceMemoryAllocator*) ()
   from /oneflow/third_party/tensorflow/lib/libxla_core.so
#9  0x00007ff6eae90d34 in xla::gpu::NVPTXCompiler::OptimizeHloPostLayoutAssignment(xla::HloModule*, stream_executor::StreamExecutor*, stream_executor::DeviceMemoryAllocator*) ()
   from /oneflow/third_party/tensorflow/lib/libxla_core.so
#10 0x00007ff6eaeb2711 in xla::gpu::GpuCompiler::OptimizeHloModule(xla::HloModule*, stream_executor::StreamExecutor*, stream_executor::DeviceMemoryAllocator*) ()
   from /oneflow/third_party/tensorflow/lib/libxla_core.so
#11 0x00007ff6eaeb3431 in xla::gpu::GpuCompiler::RunHloPasses(std::unique_ptr<xla::HloModule, std::default_delete<xla::HloModule> >, stream_executor::StreamExecutor*, stream_executor::DeviceMemoryAllocator*) () from /oneflow/third_party/tensorflow/lib/libxla_core.so
#12 0x00007ff6eae69755 in xla::Service::BuildExecutable(xla::HloModuleProto const&, std::unique_ptr<xla::HloModuleConfig, std::default_delete<xla::HloModuleConfig> >, xla::Backend*, stream_executor::StreamExecutor*, stream_executor::DeviceMemoryAllocator*) () from /oneflow/third_party/tensorflow/lib/libxla_core.so
#13 0x00007ff6e9578d59 in xla::LocalService::CompileExecutables(xla::XlaComputation const&, absl::lts_2020_02_25::Span<xla::Shape const* const>, xla::ExecutableBuildOptions const&) ()
   from /oneflow/third_party/tensorflow/lib/libxla_core.so
#14 0x00007ff6e9558b7e in xla::LocalClient::Compile(xla::XlaComputation const&, absl::lts_2020_02_25::Span<xla::Shape const* const>, xla::ExecutableBuildOptions const&) ()
   from /oneflow/third_party/tensorflow/lib/libxla_core.so
#15 0x00007ff700b3e9e8 in oneflow::xrt::mola::XlaGraphCompiler::BuildExecutable(std::vector<xla::Shape, std::allocator<xla::Shape> > const&, xla::Shape const&, xla::XlaComputation const&) ()
   from /oneflow/build/python_scripts/oneflow/_oneflow_internal.cpython-36m-x86_64-linux-gnu.so
#16 0x00007ff700b41ccf in oneflow::xrt::mola::XlaGraphCompiler::Compile(oneflow::xrt::XrtGraph const*, std::vector<oneflow::xrt::Parameter, std::allocator<oneflow::xrt::Parameter> > const&, std::vector<oneflow::xrt::Parameter, std::allocator<oneflow::xrt::Parameter> > const&, std::vector<oneflow::xrt::InputOutputAlias, std::allocator<oneflow::xrt::InputOutputAlias> > const&) ()
   from /oneflow/build/python_scripts/oneflow/_oneflow_internal.cpython-36m-x86_64-linux-gnu.so
#17 0x00007ff700abd4b4 in oneflow::XrtLaunchKernel<(oneflow::DeviceType)2>::BuildExecutable(std::vector<oneflow::xrt::Parameter, std::allocator<oneflow::xrt::Parameter> > const&, std::vector<oneflow::xrt::Parameter, std::allocator<oneflow::xrt::Parameter> > const&, std::vector<oneflow::xrt::InputOutputAlias, std::allocator<oneflow::xrt::InputOutputAlias> > const&, int) const ()
   from /oneflow/build/python_scripts/oneflow/_oneflow_internal.cpython-36m-x86_64-linux-gnu.so
#18 0x00007ff700abed8e in oneflow::XrtLaunchKernel<(oneflow::DeviceType)2>::ForwardDataContent(oneflow::KernelCtx const&, std::function<oneflow::Blob* (std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)>) const () from /oneflow/build/python_scripts/oneflow/_oneflow_internal.cpython-36m-x86_64-linux-gnu.so
#19 0x00007ff7002f38a8 in oneflow::Kernel::Forward(oneflow::KernelCtx const&, std::function<oneflow::Blob* (std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)>) const () from /oneflow/build/python_scripts/oneflow/_oneflow_internal.cpython-36m-x86_64-linux-gnu.so
#20 0x00007ff7002f25aa in oneflow::Kernel::Launch(oneflow::KernelCtx const&, std::function<oneflow::Blob* (std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)>) const () from /oneflow/build/python_scripts/oneflow/_oneflow_internal.cpython-36m-x86_64-linux-gnu.so
#21 0x00007ff6ffeee197 in oneflow::Actor::AsyncLaunchKernel(oneflow::KernelCtx const&, std::function<oneflow::Regst* (long)>) ()
   from /oneflow/build/python_scripts/oneflow/_oneflow_internal.cpython-36m-x86_64-linux-gnu.so
#22 0x00007ff6fff109c9 in oneflow::NormalForwardCompActor::Act() () from /oneflow/build/python_scripts/oneflow/_oneflow_internal.cpython-36m-x86_64-linux-gnu.so
#23 0x00007ff6ffeef9d2 in oneflow::Actor::TryLogActEvent(std::function<void ()> const&) const () from /oneflow/build/python_scripts/oneflow/_oneflow_internal.cpython-36m-x86_64-linux-gnu.so
#24 0x00007ff6ffef2456 in oneflow::Actor::ActUntilFail() () from /oneflow/build/python_scripts/oneflow/_oneflow_internal.cpython-36m-x86_64-linux-gnu.so
#25 0x00007ff6ffef2e75 in oneflow::Actor::HandlerNormal(oneflow::ActorMsg const&) () from /oneflow/build/python_scripts/oneflow/_oneflow_internal.cpython-36m-x86_64-linux-gnu.so
#26 0x00007ff700582149 in oneflow::Thread::PollMsgChannel(oneflow::ThreadCtx const&) () from /oneflow/build/python_scripts/oneflow/_oneflow_internal.cpython-36m-x86_64-linux-gnu.so
--Type <RET> for more, q to quit, c to continue without paging--
#27 0x00007ff70057eabd in ?? () from /oneflow/build/python_scripts/oneflow/_oneflow_internal.cpython-36m-x86_64-linux-gnu.so
#28 0x00007ff6d9f77dbe in std::execute_native_thread_routine (__p=0x7ff1a6c24980) at ../../../.././libstdc++-v3/src/c++11/thread.cc:83
#29 0x00007ff726044e65 in start_thread () from /usr/lib64/libpthread.so.0
#30 0x00007ff72566488d in clone () from /usr/lib64/libc.so.6
```

**Comment by jackalcooper** [comment]
@qianzhang613 Thanks for the feedback. I will look into it.

**Comment by qianzhang613** [comment]
> @qianzhang613 Thanks for the feedback. I will look into it.

@jackalcooper can  u reproduce this coredump ?  do u has some fix plan? thanks

**Comment by jackalcooper** [comment]
@qianzhang613 in this branch `fix_xla_segfault` it should be fixed. I have tested BERT and resnet. 
I will upload updated pip package later.

**Pull request merged**
