### PR TITLE
Dev cc merge nhwc src cs tick regst

### PR DESCRIPTION
**Pull request by chengtbf**
测试包含 nhwc， src op Critical section， tick regst 在内的综合性能表现。

### CODE REVIEW

**Comment by ouyangyu** [comment]
```
F1208 14:22:39.170758 22307 task_graph.cpp:552] Check failed: rank_id2src_tick.emplace(node->machine_id(), node).second
*** Check failure stack trace: ***
    @     0x7fb28f28542d  google::LogMessage::Fail()
    @     0x7fb28f286caa  google::LogMessage::SendToLog()
    @     0x7fb28f284eed  google::LogMessage::Flush()
    @     0x7fb28f2880d9  google::LogMessageFatal::~LogMessageFatal()
    @     0x7fb28a8ed8a5  (unknown)
    @     0x7fb28a8f7044  oneflow::Graph<>::ForEachNode()
    @     0x7fb28a8f0c6d  oneflow::TaskGraph::AddCtrlEdgeBetweenSrcDstTickAndInputOutputInSameRank()
    @     0x7fb28a9656f1  oneflow::Compiler::Compile()
    @     0x7fb28a4aaaae  oneflow::NNGraph::CompileAndInitRuntime()
    @     0x7fb289afc4bf  (unknown)
    @     0x7fb289896397  (unknown)
    @     0x55d4fff12c94  _PyMethodDef_RawFastCallKeywords
    @     0x55d4fff12db1  _PyCFunction_FastCallKeywords
    @     0x55d4fff7e9a1  _PyEval_EvalFrameDefault
    @     0x55d4ffec22b9  _PyEval_EvalCodeWithName
    @     0x55d4ffec33e5  _PyFunction_FastCallDict
    @     0x55d4ffee1b93  _PyObject_Call_Prepend
    @     0x55d4ffed495e  PyObject_Call
    @     0x55d4fff7b51a  _PyEval_EvalFrameDefault
    @     0x55d4ffec22b9  _PyEval_EvalCodeWithName
    @     0x55d4ffec33e5  _PyFunction_FastCallDict
    @     0x55d4ffee1b93  _PyObject_Call_Prepend
    @     0x55d4fff1916a  slot_tp_call
    @     0x55d4fff1a00b  _PyObject_FastCallKeywords
    @     0x55d4fff7e9a1  _PyEval_EvalFrameDefault
    @     0x55d4fff1220b  _PyFunction_FastCallKeywords
    @     0x55d4fff79e70  _PyEval_EvalFrameDefault
    @     0x55d4fff1220b  _PyFunction_FastCallKeywords
    @     0x55d4fff79e70  _PyEval_EvalFrameDefault
    @     0x55d4ffec331b  _PyFunction_FastCallDict
    @     0x55d4ffee1b93  _PyObject_Call_Prepend
    @     0x55d4fff1916a  slot_tp_call
Killing subprocess 22307
Traceback (most recent call last):
  File "/usr/local/miniconda3/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/local/miniconda3/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/usr/local/miniconda3/lib/python3.7/site-packages/oneflow/distributed/launch.py", line 211, in <module>
    main()
  File "/usr/local/miniconda3/lib/python3.7/site-packages/oneflow/distributed/launch.py", line 199, in main
    sigkill_handler(signal.SIGTERM, None)
  File "/usr/local/miniconda3/lib/python3.7/site-packages/oneflow/distributed/launch.py", line 168, in sigkill_handler
    returncode=last_return_code, cmd=cmd
subprocess.CalledProcessError: Command '['/usr/local/miniconda3/bin/python3', '-u', '/dataset/e1a63606/onebench/scripts/models/Vision/classification/image/resnet50/train.py', '--ofrecord-path', '/dataset/79846248', '--ofrecord-part-num', '256', '--num-devices-per-node', '1', '--lr', '0.512', '--momentum', '0.875', '--num-epochs', '1', '--train-batch-size', '512', '--val-batch-size', '50', '--print-interval', '10', '--exit-num', '30', '--use-fp16', '--channel-last', '--skip-eval', '--scale-grad', '--graph', '--fuse-bn-relu', '--fuse-bn-add-relu', '--use-gpu-decode']' died with <Signals.SIGABRT: 6>
```

**Comment by ouyangyu** [comment]
<p align="center">表 2021-12-08 ResNet50 graph  nsys 运行结果</p>

| [0063f81b](https://github.com/Oneflow-Inc/oneflow/commit/0063f81b) |
| :----------------------------------------------------------: |
| [ResNet50_graph_nsys_cpudecode_FP16_b512_1n1g](https://oneflow-test.oss-cn-beijing.aliyuncs.com/OneBrain/commit/dev_cc_merge_nhwc_src_cs_tick_regst/20211208/0063f81b/ResNet50-graph/nsys/1n1g/resnet50_graph_DCcpu_FP16_b512_1n1g_dev_cc_merge_nhwc_src_cs_tick_regst_20211208_180919950337993.qdrep) |
| [ResNet50_graph_nsys_cpudecode_FP32_b256_1n1g](https://oneflow-test.oss-cn-beijing.aliyuncs.com/OneBrain/commit/dev_cc_merge_nhwc_src_cs_tick_regst/20211208/0063f81b/ResNet50-graph/nsys/1n1g/resnet50_graph_DCcpu_FP32_b256_1n1g_dev_cc_merge_nhwc_src_cs_tick_regst_20211208_181047124359519.qdrep) |
| [ResNet50_graph_nsys_gpudecode_FP16_b512_1n1g](https://oneflow-test.oss-cn-beijing.aliyuncs.com/OneBrain/commit/dev_cc_merge_nhwc_src_cs_tick_regst/20211208/0063f81b/ResNet50-graph/nsys/1n1g/resnet50_graph_DCgpu_FP16_b512_1n1g_dev_cc_merge_nhwc_src_cs_tick_regst_20211208_180612073484150.qdrep) |
| [ResNet50_graph_nsys_gpudecode_FP32_b256_1n1g](https://oneflow-test.oss-cn-beijing.aliyuncs.com/OneBrain/commit/dev_cc_merge_nhwc_src_cs_tick_regst/20211208/0063f81b/ResNet50-graph/nsys/1n1g/resnet50_graph_DCgpu_FP32_b256_1n1g_dev_cc_merge_nhwc_src_cs_tick_regst_20211208_180738913798733.qdrep) |


<p align="center">表 2021-12-08 ResNet50 lazy  nsys 运行结果</p>

| [0063f81b](https://github.com/Oneflow-Inc/oneflow/commit/0063f81b) |
| :----------------------------------------------------------: |
| [ResNet50_lazy_nsys_gpudecode_FP16_b512_1n1g](https://oneflow-test.oss-cn-beijing.aliyuncs.com/OneBrain/commit/dev_cc_merge_nhwc_src_cs_tick_regst/20211208/0063f81b/ResNet50-lazy/nsys/1n1g/resnet50_lazy_FP16_b512_1n1g_dev_cc_merge_nhwc_src_cs_tick_regst_20211208_181233801726623.qdrep) |
| [ResNet50_lazy_nsys_cpudecode_FP16_b512_1n1g](https://oneflow-test.oss-cn-beijing.aliyuncs.com/OneBrain/commit/dev_cc_merge_nhwc_src_cs_tick_regst/20211208/0063f81b/ResNet50-lazy/nsys/1n1g/resnet50_lazy_FP16_b512_1n1g_dev_cc_merge_nhwc_src_cs_tick_regst_20211208_181456856694233.qdrep) |
| [ResNet50_lazy_nsys_gpudecode_FP32_b256_1n1g](https://oneflow-test.oss-cn-beijing.aliyuncs.com/OneBrain/commit/dev_cc_merge_nhwc_src_cs_tick_regst/20211208/0063f81b/ResNet50-lazy/nsys/1n1g/resnet50_lazy_FP32_b256_1n1g_dev_cc_merge_nhwc_src_cs_tick_regst_20211208_181356879949715.qdrep) |
| [ResNet50_lazy_nsys_cpudecode_FP32_b256_1n1g](https://oneflow-test.oss-cn-beijing.aliyuncs.com/OneBrain/commit/dev_cc_merge_nhwc_src_cs_tick_regst/20211208/0063f81b/ResNet50-lazy/nsys/1n1g/resnet50_lazy_FP32_b256_1n1g_dev_cc_merge_nhwc_src_cs_tick_regst_20211208_181619145943791.qdrep) |

如果想查看统计kernel的日志，可将url 进行修改，比如：
将`https://oneflow-test.oss-cn-beijing.aliyuncs.com/OneBrain/commit/dev_cc_merge_nhwc_src_cs_tick_regst/20211208/0063f81b/ResNet50-graph/nsys/1n1g/resnet50_graph_DCcpu_FP16_b512_1n1g_dev_cc_merge_nhwc_src_cs_tick_regst_20211208_180919950337993.qdrep` 的`.qdrep`，
修改成`.log`即为测试时日志；
修改成`/cudnn.log`则为开启了cuda 日志得到的文件；
修改成`/optimized_job0`可获取job图

**Comment by chengtbf** [comment]
@ouyangyu

**Comment by ouyangyu** [comment]
<p align="center">表 2021-12-08 ResNet50 graph  nsys 运行结果</p>

| [ee7df68b](https://github.com/Oneflow-Inc/oneflow/commit/ee7df68b) |
| :----------------------------------------------------------: |
| [ResNet50_graph_nsys_cpudecode_FP16_b512_1n1g](https://oneflow-test.oss-cn-beijing.aliyuncs.com/OneBrain/commit/dev_cc_merge_nhwc_src_cs_tick_regst/20211208/ee7df68b/ResNet50-graph/nsys/1n1g/resnet50_graph_DCcpu_FP16_b512_1n1g_dev_cc_merge_nhwc_src_cs_tick_regst_20211208_222204385532608.qdrep) |
| [ResNet50_graph_nsys_cpudecode_FP32_b256_1n1g](https://oneflow-test.oss-cn-beijing.aliyuncs.com/OneBrain/commit/dev_cc_merge_nhwc_src_cs_tick_regst/20211208/ee7df68b/ResNet50-graph/nsys/1n1g/resnet50_graph_DCcpu_FP32_b256_1n1g_dev_cc_merge_nhwc_src_cs_tick_regst_20211208_222329693405632.qdrep) |
| [ResNet50_graph_nsys_gpudecode_FP16_b512_1n1g](https://oneflow-test.oss-cn-beijing.aliyuncs.com/OneBrain/commit/dev_cc_merge_nhwc_src_cs_tick_regst/20211208/ee7df68b/ResNet50-graph/nsys/1n1g/resnet50_graph_DCgpu_FP16_b512_1n1g_dev_cc_merge_nhwc_src_cs_tick_regst_20211208_221856868056053.qdrep) |
| [ResNet50_graph_nsys_gpudecode_FP32_b256_1n1g](https://oneflow-test.oss-cn-beijing.aliyuncs.com/OneBrain/commit/dev_cc_merge_nhwc_src_cs_tick_regst/20211208/ee7df68b/ResNet50-graph/nsys/1n1g/resnet50_graph_DCgpu_FP32_b256_1n1g_dev_cc_merge_nhwc_src_cs_tick_regst_20211208_222025421232179.qdrep) |



<p align="center">表 2021-12-08 ResNet50 lazy  nsys 运行结果</p>

| [ee7df68b](https://github.com/Oneflow-Inc/oneflow/commit/ee7df68b) |
| :----------------------------------------------------------: |
| [ResNet50_lazy_nsys_gpudecode_FP16_b512_1n1g](https://oneflow-test.oss-cn-beijing.aliyuncs.com/OneBrain/commit/dev_cc_merge_nhwc_src_cs_tick_regst/20211208/ee7df68b/ResNet50-lazy/nsys/1n1g/resnet50_lazy_FP16_b512_1n1g_dev_cc_merge_nhwc_src_cs_tick_regst_20211208_222517762655521.qdrep) |
| [ResNet50_lazy_nsys_cpudecode_FP16_b512_1n1g](https://oneflow-test.oss-cn-beijing.aliyuncs.com/OneBrain/commit/dev_cc_merge_nhwc_src_cs_tick_regst/20211208/ee7df68b/ResNet50-lazy/nsys/1n1g/resnet50_lazy_FP16_b512_1n1g_dev_cc_merge_nhwc_src_cs_tick_regst_20211208_222736837681035.qdrep) |
| [ResNet50_lazy_nsys_gpudecode_FP32_b256_1n1g](https://oneflow-test.oss-cn-beijing.aliyuncs.com/OneBrain/commit/dev_cc_merge_nhwc_src_cs_tick_regst/20211208/ee7df68b/ResNet50-lazy/nsys/1n1g/resnet50_lazy_FP32_b256_1n1g_dev_cc_merge_nhwc_src_cs_tick_regst_20211208_222639281560988.qdrep) |
| [ResNet50_lazy_nsys_cpudecode_FP32_b256_1n1g](https://oneflow-test.oss-cn-beijing.aliyuncs.com/OneBrain/commit/dev_cc_merge_nhwc_src_cs_tick_regst/20211208/ee7df68b/ResNet50-lazy/nsys/1n1g/resnet50_lazy_FP32_b256_1n1g_dev_cc_merge_nhwc_src_cs_tick_regst_20211208_222856901248480.qdrep) |




如果想查看统计kernel的日志，可将url 进行修改，比如：
将`https://oneflow-test.oss-cn-beijing.aliyuncs.com/OneBrain/commit/dev_cc_merge_nhwc_src_cs_tick_regst/20211208/0063f81b/ResNet50-graph/nsys/1n1g/resnet50_graph_DCcpu_FP16_b512_1n1g_dev_cc_merge_nhwc_src_cs_tick_regst_20211208_180919950337993.qdrep` 的`.qdrep`，
修改成`.log`即为测试时日志；
修改成`/cudnn.log`则为开启了cuda 日志得到的文件；
修改成`/optimized_job0`可获取job图

**Pull request closed without merging**
