### PR TITLE
fix missing link for bert

### PR DESCRIPTION
**Pull request by jsonlee0x01**

### CODE REVIEW

**Comment by jsonlee0x01** [comment]
@daquexian @Ldpe2G

**Review by lijiansong — APPROVED** [review]
@daquexian @Ldpe2G updated

**Review by daquexian — APPROVED** [review]

**Comment by jsonlee0x01** [comment]
@Ldpe2G Review required

**Review by Ldpe2G — APPROVED** [review]

**Comment by jackalcooper** [comment]
close because head branch has been deleted

**Comment by jsonlee0x01** [comment]
腾讯公司友情提醒：机主暂时奔出服务区、、、呵呵

**Pull request closed without merging**
